name: CI/CD Test Pipeline Jo

on:
  push:
      branches:
          - main
  pull_request:
      branches:
          - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install install fastapi uvicorn pytest pytest-mock anyio pydantic python-dotenv

        - name: Run tests
          env:
            RF_MODEL: ${{secrets.RF_MODEL}}
            LOGISTIC_MODEL: ${{secrets.LOGISTIC_MODEL}}
            API_KEY: ${{secrets.API_KEY}}
          run: |
            pytest